/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package profit.miner.ui;

import profit.TradeManager;

/**
 *
 * @author USER
 */
public class TradePanel extends javax.swing.JPanel {
    TradeManager tradeMgr;
    /**
     * Creates new form TradePanel
     */
    public TradePanel(TradeManager mgr) {
        tradeMgr = mgr;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabTrades = new javax.swing.JTabbedPane();
        tabOpenOrders = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOpenOrders = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        cmdModifyOpenOrder = new javax.swing.JButton();
        cmdCloseOpenOrder = new javax.swing.JButton();
        tabPendingOrders = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPendingOrders = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cmdModifyPendingOrder = new javax.swing.JButton();
        cmdClosePendingOrder = new javax.swing.JButton();
        tabHistoryOrders = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistoryOrders = new javax.swing.JTable();
        tabLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLog = new javax.swing.JList<>();

        setLayout(new java.awt.CardLayout());

        tabTrades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tabOpenOrders.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        tblOpenOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblOpenOrders);

        jPanel4.add(jScrollPane4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        cmdModifyOpenOrder.setText("Modify");
        jPanel5.add(cmdModifyOpenOrder);

        cmdCloseOpenOrder.setText("Close");
        jPanel5.add(cmdCloseOpenOrder);

        jPanel4.add(jPanel5);

        tabOpenOrders.add(jPanel4, "card2");

        tabTrades.addTab("Open", tabOpenOrders);

        tabPendingOrders.setLayout(new java.awt.CardLayout());

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        tblPendingOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblPendingOrders);

        jPanel6.add(jScrollPane5);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        cmdModifyPendingOrder.setText("Modify");
        jPanel7.add(cmdModifyPendingOrder);

        cmdClosePendingOrder.setText("Delete");
        jPanel7.add(cmdClosePendingOrder);

        jPanel6.add(jPanel7);

        tabPendingOrders.add(jPanel6, "card2");

        tabTrades.addTab("Pending", tabPendingOrders);

        tabHistoryOrders.setLayout(new java.awt.CardLayout());

        tblHistoryOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblHistoryOrders);

        tabHistoryOrders.add(jScrollPane3, "card2");

        tabTrades.addTab("History", tabHistoryOrders);

        tabLog.setLayout(new java.awt.CardLayout());

        lstLog.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLog);

        tabLog.add(jScrollPane1, "card2");

        tabTrades.addTab("Log", tabLog);

        add(tabTrades, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCloseOpenOrder;
    private javax.swing.JButton cmdClosePendingOrder;
    private javax.swing.JButton cmdModifyOpenOrder;
    private javax.swing.JButton cmdModifyPendingOrder;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> lstLog;
    private javax.swing.JPanel tabHistoryOrders;
    private javax.swing.JPanel tabLog;
    private javax.swing.JPanel tabOpenOrders;
    private javax.swing.JPanel tabPendingOrders;
    private javax.swing.JTabbedPane tabTrades;
    private javax.swing.JTable tblHistoryOrders;
    private javax.swing.JTable tblOpenOrders;
    private javax.swing.JTable tblPendingOrders;
    // End of variables declaration//GEN-END:variables
}
